### ISSUE TITLE
Homework 1

### ISSUE THREAD

**Issue by Wiiktor22** [manav22/bigcorp-lotteries-api#2]
Hello @manav22,

I checked your implementation of the homework from the first module.

First of all please take a look at the homework submission rules we have attached to the README file of the homework repo and please try to follow them while submitting the next implementations: https://github.com/callstack-workshops/abbott-module-1-homework/blob/start/README.md#homework-management-
(It's important to create a PR for each homework module in order to have a convenient space for sharing feedback or answering potential questions).

Due to the fact that you have not created a PR this time, I'll leave a few comments to address - here in the issue:
1. Finale lottery script implementation is missing.
2. Random package should be installed as a regular dependency not as a dev dependency since it is used in the functionality. Please take a look at [this article](https://sentry.io/answers/npm-difference-between-dependencies/), it will help you to understand the differences between different types of dependencies.
3. I highly recommend initializing the Redis client only once - inside of the function that runs on server start (`app.listen`). Thanks to that the Redis client will be ready to use widely in the server application, instead of initializing it on each request sent by clients. Such operation performed on each request may prolong the time needed to execute a request, and it may impact the level of resource usage on your server machine.
4. In order to keep the file as readable as possible I highly recommend always placing all imports at the beginning of the file (that's a common convention in the whole JS ecosystem - I think it's valid for multiple programming languages). (This comment is related to your implementation of the `server.js` file, take a look at how we have done [that](https://github.com/callstack-workshops/abbott-module-1-homework).
5. Main entry file of your project is a `server.js` file, so in your top-level `package.json` file you should place a `server.js` file as a main property not `index.js`.
6. In the `/lotteries/:id` request handler there is no need to parse the incoming ID to int since it is used a few lines below as a string.
7. In the `/register` post request handler in order to check if the lottery with the given ID exists there is no need to fetch all lotteries and find it manually. The more efficient approach would be to just get one lottery (based on a given ID) with the usage of the `hGet` method. In case there will be no lottery with a given ID you will have an undefined value there, so that informs you such a lottery doesn't exist in your database. 
8. In the `onRegisterClick` implementation for the client you have used the for loop with`await` instead of the `Promise.all` method. In that case, that's all good but I would like to point out that there is a quite big difference between those two approaches, since one of them will be parallel and one will be sequential. Please take a look at this [article](https://dev.to/dperrymorrow/speed-up-your-code-with-promiseall-3d4i).

In case of any questions please feel free to contact us on Slack or book a 1:1 meeting! 😄

**Comment by manav22** [comment]
Thank you so much for the feedback. I have made all the recommended changes, except for the redis client and promise based call in onRegisterClick. I will book a one on one session for sure to understand further.Sent from my iPhoneOn 18-Sep-2023, at 4:22 PM, Wiktor Szlegier ***@***.***> wrote:﻿
Hello @manav22,
I checked your implementation of the homework from the first module.
First of all please take a look at the homework submission rules we have attached to the README file of the homework repo and please try to follow them while submitting the next implementations: https://github.com/callstack-workshops/abbott-module-1-homework/blob/start/README.md#homework-management-
(It's important to create a PR for each homework module in order to have a convenient space for sharing feedback or answering potential questions).
Due to the fact that you have not created a PR this time, I'll leave a few comments to address - here in the issue:

Finale lottery script implementation is missing.
Random package should be installed as a regular dependency not as a dev dependency since it is used in the functionality. Please take a look at this article, it will help you to understand the differences between different types of dependencies.
I highly recommend initializing the Redis client only once - inside of the function that runs on server start (app.listen). Thanks to that the Redis client will be ready to use widely in the server application, instead of initializing it on each request sent by clients. Such operation performed on each request may prolong the time needed to execute a request, and it may impact the level of resource usage on your server machine.
In order to keep the file as readable as possible I highly recommend always placing all imports at the beginning of the file (that's a common convention in the whole JS ecosystem - I think it's valid for multiple programming languages). (This comment is related to your implementation of the server.js file, take a look at how we have done that.
Main entry file of your project is a server.js file, so in your top-level package.json file you should place a server.js file as a main property not index.js.
In the /lotteries/:id request handler there is no need to parse the incoming ID to int since it is used a few lines below as a string.
In the /register post request handler in order to check if the lottery with the given ID exists there is no need to fetch all lotteries and find it manually. The more efficient approach would be to just get one lottery (based on a given ID) with the usage of the hGet method. In case there will be no lottery with a given ID you will have an undefined value there, so that informs you such a lottery doesn't exist in your database.
In the onRegisterClick implementation for the client you have used the for loop withawait instead of the Promise.all method. In that case, that's all good but I would like to point out that there is a quite big difference between those two approaches, since one of them will be parallel and one will be sequential. Please take a look at this article.

In case of any questions please feel free to contact us on Slack or book a 1:1 meeting! 😄
